#ifndef ALBUMCOVERS_GLOBAL_H
#define ALBUMCOVERS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ALBUMCOVERS_LIBRARY)
#  define ALBUMCOVERSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ALBUMCOVERSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ALBUMCOVERS_GLOBAL_H
