#ifndef SIDEBARPLUGINTEST_GLOBAL_H
#define SIDEBARPLUGINTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIDEBARPLUGINTEST_LIBRARY)
#  define SIDEBARPLUGINTESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIDEBARPLUGINTESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIDEBARPLUGINTEST_GLOBAL_H
