#ifndef PHONONBACKEND_GLOBAL_H
#define PHONONBACKEND_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHONONBACKEND_LIBRARY)
#  define PHONONBACKENDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PHONONBACKENDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PHONONBACKEND_GLOBAL_H
