#ifndef M3UPLAYLISTSTORAGE_GLOBAL_H
#define M3UPLAYLISTSTORAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(M3UPLAYLISTSTORAGE_LIBRARY)
#  define M3UPLAYLISTSTORAGESHARED_EXPORT Q_DECL_EXPORT
#else
#  define M3UPLAYLISTSTORAGESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // M3UPLAYLISTSTORAGE_GLOBAL_H
