#ifndef GUICONTROLLER_GLOBAL_H
#define GUICONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GUICONTROLLER_LIBRARY)
#  define GUICONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GUICONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GUICONTROLLER_GLOBAL_H
