#ifndef LASTFMINFORESOLVER_GLOBAL_H
#define LASTFMINFORESOLVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LASTFMINFORESOLVER_LIBRARY)
#  define LASTFMINFORESOLVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LASTFMINFORESOLVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LASTFMINFORESOLVER_GLOBAL_H
