#ifndef TOUCHEVENTFILTERPLUGIN_GLOBAL_H
#define TOUCHEVENTFILTERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOUCHEVENTFILTERPLUGIN_LIBRARY)
#  define TOUCHEVENTFILTERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOUCHEVENTFILTERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOUCHEVENTFILTERPLUGIN_GLOBAL_H
