#ifndef PLUGINSYSTEM_GLOBAL_H
#define PLUGINSYSTEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGINSYSTEM_LIBRARY)
#  define PLUGINSYSTEMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINSYSTEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINSYSTEM_GLOBAL_H
