#ifndef SPOTIFYPLUGIN_GLOBAL_H
#define SPOTIFYPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SPOTIFYPLUGIN_LIBRARY)
#  define SPOTIFYPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SPOTIFYPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SPOTIFYPLUGIN_GLOBAL_H
