#ifndef HACKINGWIDGET_GLOBAL_H
#define HACKINGWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HACKINGWIDGET_LIBRARY)
#  define HACKINGWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HACKINGWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HACKINGWIDGET_GLOBAL_H
