#ifndef PLAYERWIDGETII_GLOBAL_H
#define PLAYERWIDGETII_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLAYERWIDGETII_LIBRARY)
#  define PLAYERWIDGETIISHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLAYERWIDGETIISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLAYERWIDGETII_GLOBAL_H
