#ifndef SONGTREEWIDGET_GLOBAL_H
#define SONGTREEWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SONGTREEWIDGET_LIBRARY)
#  define SONGTREEWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SONGTREEWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SONGTREEWIDGET_GLOBAL_H
