#ifndef SAFRIPLAYERWIDGET_GLOBAL_H
#define SAFRIPLAYERWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLAYERWIDGET_LIBRARY)
#  define PLAYERWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLAYERWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SAFRIPLAYERWIDGET_GLOBAL_H
