#ifndef AUDIOSQLSTORAGE_GLOBAL_H
#define AUDIOSQLSTORAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUDIOSQLSTORAGE_LIBRARY)
#  define AUDIOSQLSTORAGESHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUDIOSQLSTORAGESHARED_EXPORT Q_DECL_IMPORT
#endif

#define DATABASE_VERSION 3

#endif // AUDIOSQLSTORAGE_GLOBAL_H
