#ifndef DARKBLUESKIN_GLOBAL_H
#define DARKBLUESKIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DARKBLUESKIN_LIBRARY)
#  define DARKBLUESKINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DARKBLUESKINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DARKBLUESKIN_GLOBAL_H
