#ifndef PLAYBACKCONTROLLER_GLOBAL_H
#define PLAYBACKCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLAYBACKCONTROLLER_LIBRARY)
#  define PLAYBACKCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLAYBACKCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLAYBACKCONTROLLER_GLOBAL_H
