#ifndef SAFRIMOBILEGUIQML_GLOBAL_H
#define SAFRIMOBILEGUIQML_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SAFRIMOBILEGUIQML_LIBRARY)
#  define SAFRIMOBILEGUIQMLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SAFRIMOBILEGUIQMLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SAFRIMOBILEGUIQML_GLOBAL_H
