#ifndef AUDIOCOLLECTION_GLOBAL_H
#define AUDIOCOLLECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUDIOCOLLECTION_LIBRARY)
#  define AUDIOCOLLECTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUDIOCOLLECTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AUDIOCOLLECTION_GLOBAL_H
