#ifndef SAFRI2SKIN_GLOBAL_H
#define SAFRI2SKIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SAFRI2SKIN_LIBRARY)
#  define SAFRI2SKINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SAFRI2SKINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SAFRI2SKIN_GLOBAL_H
