#ifndef PLAYLISTWIDGET_GLOBAL_H
#define PLAYLISTWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLAYLISTWIDGET_LIBRARY)
#  define PLAYLISTWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLAYLISTWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLAYLISTWIDGET_GLOBAL_H
